
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase'; // We will create this type definition file later

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl) {
  throw new Error("Missing environment variable NEXT_PUBLIC_SUPABASE_URL");
}
if (!supabaseAnonKey) {
  throw new Error("Missing environment variable NEXT_PUBLIC_SUPABASE_ANON_KEY");
}

// Create a single supabase client for interacting with your database
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);

// Note: The `Database` generic type will be generated by Supabase CLI
// after you define your database schema. For now, we can use a placeholder
// or proceed without it and add it later.
// Example placeholder if you don't have supabase.ts types yet:
// export const supabase = createClient(supabaseUrl, supabaseAnonKey);
